config/routes.rb
Rails.application.routes.draw do
  resources :sender_addresses

  resources :number_invoices

  resources :number_guides

  resources :addressees

  resources :senders

  resources :creditos

  resources :monedas

  resources :elementos

  resources :facturas do
    collection { 
      get :values_guia_remision 
      get :values_item_guia
      get :values_factura_guia_id
      get :anular_factura
    }
  end

  resources :measures
  resources :units

  resources :guides do
    collection { 
      get :add_objeto 
      get :anular_guide
    }
  end  
  resources :backs
  resources :fronts
  resources :provinces
  resources :districts
  resources :departments
  devise_for :admins
  get 'home/index'

   root 'guides#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
        #user ||= User.new # guest user (not logged in)
        #if user.admin?
        #    can :manage, :all
        #else
        #    can :read, :all
        #end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/addressee.rb
class Addressee < ActiveRecord::Base
	has_many :guide
	validates_presence_of :name_reason
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/back.rb
class Back < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/credito.rb
class Credito < ActiveRecord::Base
	has_many :facturas
	validates_presence_of :nombre
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :provinces

	#has_many :partidas, :class_name => 'Guide', :foreign_key => 'partida_department_id'
  	#has_many :llegada, :class_name => 'Guide', :foreign_key => 'llegada_department_id'
  	validates_presence_of :nombre

  	accepts_nested_attributes_for :provinces, :reject_if => :all_blank, :allow_destroy => true
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :province
	validates_presence_of :nombre

end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :factura
  belongs_to :moneda
  belongs_to :item
  belongs_to :guide  
end

app/models/factura.rb
class Factura < ActiveRecord::Base
  belongs_to :guide
  belongs_to :credito
  belongs_to :number_invoice
  belongs_to :sender_address
  has_many :elementos
  belongs_to :moneda
  #accepts_nested_attributes_for :elementos, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :elementos, reject_if: proc { |attributes| attributes[:precio_venta].blank? }, :allow_destroy => true 

  validates_uniqueness_of :numero, message: '- Ya Existe'
  validates_presence_of :numero, message: '- En blanco'  
  validates_presence_of :fecha, message: '- En blanco'
  validates_presence_of :sender_address_id, message: '- En blanco'  
  validates_presence_of :moneda_id, message: '- En blanco'  
  #validates_presence_of :ruc, message: '- En blanco'
  #validates_presence_of :guide_id, message: '- En blanco'
  validates_presence_of :valor_venta, message: '- En blanco'
  validates_presence_of :igv, message: '- En blanco'
  validates_presence_of :precio_venta, message: '- En blanco'

end

app/models/front.rb
class Front < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/guide.rb
class Guide < ActiveRecord::Base

	belongs_to :partida_department, :class_name => 'Department', :foreign_key => 'partida_department_id'
	belongs_to :partida_province, :class_name => 'Province', :foreign_key => 'partida_province_id'
  belongs_to :partida_district, :class_name => 'District', :foreign_key => 'partida_district_id'

  belongs_to :llegada_department, :class_name => 'Department', :foreign_key => 'llegada_department_id'
  belongs_to :llegada_province, :class_name => 'Province', :foreign_key => 'llegada_province_id'
  belongs_to :llegada_district, :class_name => 'District', :foreign_key => 'llegada_district_id'

  has_many :items
  has_many :facturas

  belongs_to :front
  belongs_to :back

  belongs_to :sender
  belongs_to :addressee

  belongs_to :number_guide
  belongs_to :elemento

  #accepts_nested_attributes_for :items, reject_if: proc { |attributes| attributes[:codigo].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true

  validates_uniqueness_of :numero_remision_guia, message: '- Ya Existe'
  validates_presence_of :numero_remision_guia, message: '- En blanco'
  validates_presence_of :fecha_emision
  validates_presence_of :fecha_inicio_traslado, message: '- En blanco'
  validates_presence_of :sender_id, message: '- En blanco'
  validates_presence_of :addressee_id, message: '- En blanco' 
  validates_presence_of :partida_direccion, message: '- En blanco' 
  validates_presence_of :partida_district_id, message: '- En blanco'
  validates_presence_of :llegada_direccion, message: '- En blanco'
  validates_presence_of :llegada_district_id, message: '- En blanco'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :guide
	belongs_to :unit
	belongs_to :measure
	belongs_to :elemento
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
	has_many :facturas
	validates_presence_of :nombre
	validates_presence_of :simbolo
end

app/models/number_guide.rb
class NumberGuide < ActiveRecord::Base
	has_many :guides
	validates_presence_of :numero
	validates_uniqueness_of :numero
end

app/models/province.rb
class Province < ActiveRecord::Base
	belongs_to :department
	has_many :districts

	accepts_nested_attributes_for :districts, :reject_if => :all_blank, :allow_destroy => true
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sender.rb
class Sender < ActiveRecord::Base
	has_many :guide
	has_many :facturas
	has_many :sender_addresses
	validates_presence_of :name_reason
		
	accepts_nested_attributes_for :sender_addresses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :items	

	validates_presence_of :nombre
	validates_presence_of :und
end

app/controllers/units_controller.rb
class UnitsController < InheritedResources::Base
	def permitted_params
		params.permit!
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.haml
= form_for @unit, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")}"
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :nombre, class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :nombre, class: 'form-control'
  .form-group
    = f.label :und, class: 'col-sm-2 control-label'
    .col-sm-1
      = f.text_field :und, class: 'form-control'
  .form-group
    .col-sm-2
    .col-sm-4
      = f.submit 'Guardar', class: 'btn btn-default btn-sm'


:javascript
  $('*').on('keydown', function(e){
      if (e.keyCode === 13) {
          var inputs = $(this).parents("form").eq(0).find(":input");
          var idx = inputs.index(this);
          if (idx == inputs.length - 1) {
              inputs[0].select()
          } else {
              inputs[idx + 1].focus(); //  handles submit buttons
              inputs[idx + 1].select();
          }
          return false;
      }
  });

app/views/units/edit.html.haml
- page_title!('Editando unit')

#region-units.container

  .region
    .page-header
      %h1
        Edit
        %b
          Unidad

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to '<span class="glyphicon glyphicon-eye-open"></span> Ver'.html_safe, @unit, class: 'btn btn-info btn-sm'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Regresar'.html_safe, 'javascript:history.back(-1)', class: 'btn btn-warning btn-sm'

app/views/units/index.html.haml
#region-units

  .region
    .page-header
      %h1 Unidades

    .region      
      .admin-control
        = link_to '<span class="glyphicon glyphicon-plus"></span> Crear'.html_safe, new_unit_path, class: 'btn btn-primary btn-lg'
      %br
      .row 
        .col-sm-7
          .table-responsive
            %table.table.table-hover.table-condensed.table-bordered
              %tr.well
                %th #id
                %th Nombre
                %th Und
                %th Acciones

              - @units.each do |unit|
                %tr
                  %td= unit.id
                  %td= unit.nombre
                  %td= unit.und
                  %td
                    = link_to '<span class="glyphicon glyphicon-eye-open"></span> Ver'.html_safe, unit, class: 'btn btn-info btn-sm'
                    = link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_unit_path(unit), class: 'btn btn-success btn-sm'
                    = link_to '<span class="glyphicon glyphicon-trash"></span> Eliminar'.html_safe, unit, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger btn-sm'

app/views/units/new.html.haml
- page_title!('Creando unit')

#region-units.container

  .region
    .page-header
      %h1
        Crear
        %b
          Unidad

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Regresar'.html_safe, 'javascript:history.back(-1)', class: 'btn btn-warning btn-sm'

app/views/units/show.html.haml
#region-units.container
  .region
    .page-header
      %h1= page_title!('Unidad')

  .region
    %p
      %b Nombre:
      = @unit.nombre
    %p
      %b Und:
      = @unit.und

  .region    
    .admin-controls
      = link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_unit_path(@unit), class: 'btn btn-success btn-sm'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Regresar'.html_safe, units_path, class: 'btn btn-warning btn-sm'