config/routes.rb
Rails.application.routes.draw do
  resources :sender_addresses

  resources :number_invoices

  resources :number_guides

  resources :addressees

  resources :senders

  resources :creditos

  resources :monedas

  resources :elementos

  resources :facturas do
    collection { 
      get :values_guia_remision 
      get :values_item_guia
      get :values_factura_guia_id
      get :anular_factura
    }
  end

  resources :measures
  resources :units

  resources :guides do
    collection { 
      get :add_objeto 
      get :anular_guide
    }
  end  
  resources :backs
  resources :fronts
  resources :provinces
  resources :districts
  resources :departments
  devise_for :admins
  get 'home/index'

   root 'guides#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
        #user ||= User.new # guest user (not logged in)
        #if user.admin?
        #    can :manage, :all
        #else
        #    can :read, :all
        #end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/addressee.rb
class Addressee < ActiveRecord::Base
	has_many :guide
	validates_presence_of :name_reason
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/back.rb
class Back < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/credito.rb
class Credito < ActiveRecord::Base
	has_many :facturas
	validates_presence_of :nombre
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :provinces

	#has_many :partidas, :class_name => 'Guide', :foreign_key => 'partida_department_id'
  	#has_many :llegada, :class_name => 'Guide', :foreign_key => 'llegada_department_id'
  	validates_presence_of :nombre

  	accepts_nested_attributes_for :provinces, :reject_if => :all_blank, :allow_destroy => true
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :province
	validates_presence_of :nombre

end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :factura
  belongs_to :moneda
  belongs_to :item
  belongs_to :guide  
end

app/models/factura.rb
class Factura < ActiveRecord::Base
  belongs_to :guide
  belongs_to :credito
  belongs_to :number_invoice
  belongs_to :sender_address
  has_many :elementos
  belongs_to :moneda
  #accepts_nested_attributes_for :elementos, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :elementos, reject_if: proc { |attributes| attributes[:precio_venta].blank? }, :allow_destroy => true 

  validates_uniqueness_of :numero, message: '- Ya Existe'
  validates_presence_of :numero, message: '- En blanco'  
  validates_presence_of :fecha, message: '- En blanco'
  validates_presence_of :sender_address_id, message: '- En blanco'  
  validates_presence_of :moneda_id, message: '- En blanco'  
  #validates_presence_of :ruc, message: '- En blanco'
  #validates_presence_of :guide_id, message: '- En blanco'
  validates_presence_of :valor_venta, message: '- En blanco'
  validates_presence_of :igv, message: '- En blanco'
  validates_presence_of :precio_venta, message: '- En blanco'

end

app/models/front.rb
class Front < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/guide.rb
class Guide < ActiveRecord::Base

	belongs_to :partida_department, :class_name => 'Department', :foreign_key => 'partida_department_id'
	belongs_to :partida_province, :class_name => 'Province', :foreign_key => 'partida_province_id'
  belongs_to :partida_district, :class_name => 'District', :foreign_key => 'partida_district_id'

  belongs_to :llegada_department, :class_name => 'Department', :foreign_key => 'llegada_department_id'
  belongs_to :llegada_province, :class_name => 'Province', :foreign_key => 'llegada_province_id'
  belongs_to :llegada_district, :class_name => 'District', :foreign_key => 'llegada_district_id'

  has_many :items
  has_many :facturas

  belongs_to :front
  belongs_to :back

  belongs_to :sender
  belongs_to :addressee

  belongs_to :number_guide
  belongs_to :elemento

  #accepts_nested_attributes_for :items, reject_if: proc { |attributes| attributes[:codigo].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true

  validates_uniqueness_of :numero_remision_guia, message: '- Ya Existe'
  validates_presence_of :numero_remision_guia, message: '- En blanco'
  validates_presence_of :fecha_emision
  validates_presence_of :fecha_inicio_traslado, message: '- En blanco'
  validates_presence_of :sender_id, message: '- En blanco'
  validates_presence_of :addressee_id, message: '- En blanco' 
  validates_presence_of :partida_direccion, message: '- En blanco' 
  validates_presence_of :partida_district_id, message: '- En blanco'
  validates_presence_of :llegada_direccion, message: '- En blanco'
  validates_presence_of :llegada_district_id, message: '- En blanco'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :guide
	belongs_to :unit
	belongs_to :measure
	belongs_to :elemento
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_many :guides
	validates_presence_of :nombre
end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
	has_many :facturas
	validates_presence_of :nombre
	validates_presence_of :simbolo
end

app/models/number_guide.rb
class NumberGuide < ActiveRecord::Base
	has_many :guides
	validates_presence_of :numero
	validates_uniqueness_of :numero
end

app/models/province.rb
class Province < ActiveRecord::Base
	belongs_to :department
	has_many :districts

	accepts_nested_attributes_for :districts, :reject_if => :all_blank, :allow_destroy => true
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sender.rb
class Sender < ActiveRecord::Base
	has_many :guide
	has_many :facturas
	has_many :sender_addresses
	validates_presence_of :name_reason
		
	accepts_nested_attributes_for :sender_addresses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :items	

	validates_presence_of :nombre
	validates_presence_of :und
end

app/controllers/senders_controller.rb
class SendersController < InheritedResources::Base	
	def permitted_params
		params.permit!
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.haml
= form_for @sender, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @sender.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sender.errors.count, "error")}"
      %ul
        - @sender.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label "Nombre / Razon Social", class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :name_reason, class: 'form-control'
  .form-group
    = f.label :ruc, class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :ruc, class: 'form-control'
  .form-group
    = f.label "DNI", class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :identity_document, class: 'form-control'


  %h3 
    Direcciones
    %small del Remitente
  %hr

  
  = f.fields_for :sender_addresses do |sender_addres|
    = render 'sender_address_fields', :f => sender_addres
  #direcciones
    = link_to_add_association '<span class="glyphicon glyphicon-plus"></span> Agregar'.html_safe, f, :sender_addresses, class: 'btn btn-primary'
      
  %br
  .form-group
    .col-sm-4
      = f.submit 'Guardar', class: 'btn btn-default'


:javascript
  $('*').on('keydown', function(e){
      if (e.keyCode === 13) {
          var inputs = $(this).parents("form").eq(0).find(":input");
          var idx = inputs.index(this);
          if (idx == inputs.length - 1) {
              inputs[0].select()
          } else {
              inputs[idx + 1].focus(); //  handles submit buttons
              inputs[idx + 1].select();
          }
          return false;
      }
  });

app/views/senders/_sender_address_fields.html.haml
.form-group.nested-fields
	.col-sm-6
		= f.text_field :direccion, class: 'form-control', placeholder: ''
	.col-sm-3	
		= link_to_remove_association '<span class="glyphicon glyphicon-trash"></span>'.html_safe , f, class: 'btn btn-danger'


app/views/senders/edit.html.haml
- page_title!('Editando sender')

#region-senders.container

  .region
    .page-header
      %h1
        Edit
        %b
          Remitente

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to '<span class="glyphicon glyphicon-eye-open"></span> Ver'.html_safe, @sender, class: 'btn btn-info'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Regresar'.html_safe, 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/senders/index.html.haml
.page-header    
  %h1= page_title!('Remitentes')
= link_to '<span class="glyphicon glyphicon-plus"></span> Crear'.html_safe, new_sender_path, class: 'btn btn-primary btn-lg'
%br
%br
.table-responsive
  %table.table.table-condensed.table-hover.table-bordered
    %tr.well
      %th Nombre / Razon
      %th Ruc
      %th Documento Identidad
      %th Acciones


    - @senders.each do |sender|
      %tr
        %td= sender.name_reason
        %td= sender.ruc
        %td= sender.identity_document
        %td          
          = link_to '<span class="glyphicon glyphicon-eye-open"></span> Ver'.html_safe, sender, class: 'btn btn-info'
          = link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_sender_path(sender), class: 'btn btn-success'
          = link_to '<span class="glyphicon glyphicon-trash"></span> Eliminar'.html_safe, sender, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/senders/new.html.haml
.page-header
  %h1 
    Crear 
    %strong Remitente  
= render 'form'

app/views/senders/show.html.haml
#region-senders.container
  .region
    .page-header
      %h1= page_title!('Remitente')

  .region
    .row
      .col-sm-6
        %table.table.table-condensed.table-bordered
          %tr
            %td.well.text-right Nombre / Razon Social : 
            %td= @sender.name_reason
          %tr
            %td.well.text-right Ruc : 
            %td= @sender.ruc
          %tr
            %td.well.text-right DNI : 
            %td= @sender.identity_document   
      
    %h3
      Direcciones
      %small del Remitente
    %hr
    .row
      .col-sm-6
        
        %table.table.table-condensed.table-bordered
          - i = 1
          - @sender.sender_addresses.each do |sender_address|
            %tr
              %td.well.text-right
                Direccion
                = i
                \:
                - i  = i + 1
              %td= sender_address.direccion

      
  .region
    = link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_sender_path(@sender), class: 'btn btn-success'
    = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Regresar'.html_safe, senders_path, class: 'btn btn-warning'